apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: plataforma
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <ECR_REGISTRY>/plataforma/frontend:<TAG>
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: https://api.tudominio.pe
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /catalogo
              port: 3000
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: plataforma
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 3000
